### ISSUE TITLE
Discriminate Python2 and Python3 CFBundleIdentifier

### ISSUE THREAD

**Issue by lucasg** [Kapeli/feeds#12]
Hi,

I'm not sure where to report this feature request, but i figured here would be a good place for it. I often use the Dashs docsets for Python 2 along with Python 3 (since most Python projects have to support both versions) and unfortunately the `CFBundleIdentifier` is the same for both packages :

![image](https://user-images.githubusercontent.com/2520861/29311521-8b463d88-81b2-11e7-9e82-dfdab8437f00.png)

Which means I can't search for an API for a particular Python version (`print` is a function in python3 where it's a statement in Python2)  :

![image](https://user-images.githubusercontent.com/2520861/29311643-0a696158-81b3-11e7-8a46-2499ec8d3b78.png)

The fix is actually quite simple : changing the `CFBundleIdentifier` on both docsets's `Info.plist` ( I use `python2` and `python3` as identifiers). For the time being I do the modifications on my machine, but there are regularly overwritten by updates so I might as well try to upstream it.

The real fix would be to propose a user-configured overrides for package identifiers (or aliases) but that may be over-engineered a bit. Anyway if you accept this minor change I would be glad.

**Comment by Kapeli** [comment]
This isn't an issue in Dash as you can choose between different docsets at search time, as well as modify the docset keyword so you can search only a specific version of Python.

![screen shot 2017-08-15 at 14 19 30](https://user-images.githubusercontent.com/1445635/29314038-c7edafa2-81c4-11e7-983f-face86037a39.png)
