### ISSUE TITLE
Exclude Angular links from AngularJS

### ISSUE THREAD

**Issue by cmalard** [Kapeli/feeds#13]
Hello there,

As Angular JS (1) has been renamed AngularJS, it should not include Angular(TS) (2+) docsets :
https://github.com/Kapeli/feeds/blob/ff6a4cdafe718b180d5a725443fbb0dd1f9cec85/AngularJS.xml#L12-L35

Could you please remove them ? :-)

**Comment by Kapeli** [comment]
Those docsets are actually for "Angular for JavaScript". The AngularTS docsets are in the AngularTS.xml feed.

Please note though that I've deprecated all the Angular*.xml feeds and now only update Angular.xml. The Angular.xml feed contains docsets for Angular versions from 1.x to 4.x.

I know AngularJS 1.x isn't really "Angular", but I can't clutter the interface with "Angular", "AngularTS", "AngularJS" and so on. I'd rather just have one "Angular" option.

// @trollixx You should make Zeal use the Angular.xml feed if it doesn't already.

**Comment by cmalard** [comment]
@Kapeli please reconsider this and reopen.
I'm actually developing apps in Angular AND AngularJS. I need *both* docs.
Those frameworks have little in common and should not be merged in the same docset.
This is actually necessary to keep Angular and AngularJS separate.

**Comment by trollixx** [comment]
@cmalard Your problem has nothing to do with Dash feeds, but rather Zeal lacking ability to have different versions of the same docset installed simultaneously (zealdocs/zeal#208). Please, do not bother @Kapeli if something works in Dash, but does not in Zeal. He has no obligation to provide any kind of support for Zeal users.

@Kapeli Thanks for the update, I'll replace `AngularJS` and `AngularTS` with just `Angular`. Should I also remove `Angular.dart`? It's kind of outdated.

**Comment by cmalard** [comment]
Well... sorry to "bother".
Of course, this would not be an issue for me as a Zeal user if I could easily access different versions simultaneously.

But those are 2 different frameworks : their language, what they provide, even their names.
