### ISSUE TITLE
Incorrect reference links in Dojo docset

### ISSUE THREAD

**Issue by jason0x43** [Kapeli/feeds#6]
Once upon a time, the links to the Dojo reference documentation on API pages (e.g., "See the [dojo/dom-construct reference documentation] for more information." on the dojo dom-construct page) actually linked to the online reference documentation. Now they just link back to the currently displayed API page. It'd be awesome if those links were external again.

**Comment by Kapeli** [comment]
This should now be fixed.

Please note that this is not the place to report issues about docsets. It's best if you contact me directly in the future: https://kapeli.com/contact.
