### ISSUE TITLE
Missing ReactNative.xml in feeds

### ISSUE THREAD

**Issue by epitaphmike** [Kapeli/feeds#8]
I noticed that there is no ReactNative.xml in your feeds folder.

**Comment by epitaphmike** [comment]
I use the React as a comparison for ReactNative since they are similar and it seems in Dash you can only download React and React Native via User Contributed Docsets. Listed below are the source locations when Dash downloads the docsets.

http://newyork.kapeli.com/feeds/zzz/user_contributed/build/React/versions/0.13.1/React.tgz
http://london3.kapeli.com/feeds/zzz/user_contributed/build/React_Native/versions/0.5.0

While in you github feeds list you list http://london.kapeli.com/feeds/React.tgz in the React.xml which has React v0.13.3
https://github.com/Kapeli/feeds/blob/master/React.xml

Is the listed React Docset not available to download via Dash? I could not find it, plus the layout is different.

Thanks

**Comment by Kapeli** [comment]
Please see https://github.com/chenglou/react-dash/issues/9.

**Comment by epitaphmike** [comment]
That's great! Are there any plans to do an official React Native? I will
continue to support my docset until there is.

I was in the middle of doing a Babel docset as well. Just a heads up.

**Comment by Kapeli** [comment]
No plans for React Native. I've only received 5 requests for it.

**Comment by epitaphmike** [comment]
Sounds good. Hopefully with the popularity of React, React Native will
grow. I will continue to support their doc updates on my end.

Speaking of which. I pushed the 0.5.0 docset in the 0.8.0 release yesterday
by accident.

I am fixing the files and I will recommit with the correct version of the
docset.

Just curious, has there been any interest in a Babel docset? I was thinking
about making a set.

Thanks and nice work on Dash 3 as well.

**Comment by Kapeli** [comment]
Babel got 2 requests, so not much.

**Comment by epitaphmike** [comment]
Sounds good. Thanks
